### ISSUE TITLE
Crashes in multiplayer

### ISSUE THREAD

**Issue by hoyes127** [bmaupin/react-civ5save#7] opened 2018-11-01 19:25 UTC
played this multiplayer game and host started it with wrong turn mode (hybrid). found out about this editor later around turn 100 and changed it to simultanious. we played fine but when i saved it and tried to reload it, it just crashes after the load. sometimes i can play 1 turn before crashing

last save file

[Askia_0273 AD-1993 (3) (1) (1) (1).zip](https://github.com/bmaupin/civ5save-editor/files/2539789/Askia_0273.AD-1993.3.1.1.1.zip)

**Comment by bmaupin** [comment] 2018-11-02 17:30
Interesting, I'll see what I can do to help. First of all, I'll need some more information:

- It looks like you're using Steam. Have you tried [verifying the integrity of the game files](https://support.steampowered.com/kb/2037-QEUH-3335/verify-integrity-of-game-cache)?
- Are you using any mods?
- Are all players using the same version of Civ 5 with the same mods and DLC installed?
- You said you changed the turn type to simultaneous, but when I open the save file with the app it says the turn type is sequential. Which turn type did you change it to?
- Have you tried changing it back to hybrid and seeing if that works?
- It looks like you're at turn 273 now. Have you tried loading any autosaves from any previous turns?

Thanks!

**Comment by bmaupin** [comment] 2018-11-13 18:59
@hoyes127 Any update on this? I'd love to help if I can. Thanks!

**Comment by hoyes127** [comment] 2018-11-14 16:17
quite a long time since we played on this game but i remember trying to verify game files and it always replaced 1 folder. it still crashed after loading.
We play default civ
we have the same version and are playing with all dlc's enabled
we started with hybrid then i changed it to simultaneus. resulting in crash after one session. i tried fixing it by changing the turn types, maybe thats why you're seeing sequential.
when changing it back to hybrid we can play one round until it crashes
the only load file that works is the file before i changed the turn type (using this website)

**Comment by bmaupin** [comment] 2018-11-15 18:24
> when changing it back to hybrid we can play one round until it crashes
Hmm, that's really odd. Can you attach a couple more files to this bug (if you still have them)?:

1. The file before you made any changes
2. The file after you changed it back to hybrid

If you changed it back to hybrid and it's still crashing, then there's either a bug with my app or your file's corrupted somehow. If I can get the different versions I can compare them and try to figure out the cause.

Thanks!

**Comment by bmaupin** [comment] 2018-12-18 19:11
Any luck on getting those files? Thanks!

**Comment by bmaupin** [comment] 2019-01-02 18:07
I'll go ahead and close this issue, but if you're able to get those [extra files I requested](https://github.com/bmaupin/civ5save-editor/issues/7#issuecomment-439141260) feel free to reopen it. Thanks!

**Closed as completed by bmaupin** 2019-01-02 18:07 UTC
